service: api

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  authorize:
    handler: api/authorize.authorize
  login:
    handler: api/login.login
    events:
      - http:
          path: login
          method: post
          cors: true
  createUser:
    handler: api/users/createUser.createUser
    events:
      - http:
          path: user
          method: post
          cors: true
  getUser:
    handler: api/users/getUser.getUser
    events:
      - http:
          path: user
          method: get
          cors: true
  getUsers:
    handler: api/users/getUsers.getUsers
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer: authorize
  updateUser:
    handler: api/users/updateUser.updateUser
    events:
      - http:
          path: user
          method: put
          cors: true
  deleteUser:
    handler: api/users/deleteUser.deleteUser
    events:
      - http:
          path: user
          method: delete
          cors: true
  createShoppingList:
    handler: api/shoppingLists/createShoppingList.createShoppingList
    events:
      - http:
          path: shoppingList
          method: post
          cors: true
  getShoppingList:
    handler: api/shoppingLists/getShoppingList.getShoppingList
    events:
      - http:
          path: shoppingList
          method: get
          cors: true
  getShoppingLists:
    handler: api/shoppingLists/getShoppingLists.getShoppingLists
    events:
      - http:
          path: shoppingLists
          method: get
          cors: true
  updateShoppingList:
    handler: api/shoppingLists/updateShoppingList.updateShoppingList
    events:
      - http:
          path: shoppingList
          method: put
          cors: true
  deleteShoppingList:
    handler: api/shoppingLists/deleteShoppingList.deleteShoppingList
    events:
      - http:
          path: shoppingList
          method: delete
          cors: true
  createShoppingItem:
    handler: api/shoppingItems/createShoppingItem.createShoppingItem
    events:
      - http:
          path: shoppingItem
          method: post
          cors: true
  getShoppingItem:
    handler: api/shoppingItems/getShoppingItem.getShoppingItem
    events:
      - http:
          path: shoppingItem
          method: get
          cors: true
  getShoppingItems:
    handler: api/shoppingItems/getShoppingItems.getShoppingItems
    events:
      - http:
          path: shoppingItems
          method: get
          cors: true
  updateShoppingItem:
    handler: api/shoppingItems/updateShoppingItem.updateShoppingItem
    events:
      - http:
          path: shoppingItem
          method: put
          cors: true
  deleteShoppingItem:
    handler: api/shoppingItems/deleteShoppingItem.deleteShoppingItem
    events:
      - http:
          path: shoppingItem
          method: delete
          cors: true
  getStatistic:
    handler: api/statistic/getStatistic.getStatistic
    events:
      - http:
          path: statistic
          method: get
          cors: true
          authorizer: authorize
  getBill:
    handler: api/bills/getBill.getBill
    events:
      - http:
          path: bill
          method: get
          cors: true
  getBillAndSave:
    handler: api/bills/getBillAndSave.getBillAndSave
    events:
      - http:
          path: savebill
          method: get
          cors: true
  checkBill:
    handler: api/bills/checkBill.checkBill
    events:
      - http:
          path: checkbill
          method: get
          cors: true
  createUserForBill:
    handler: api/bills/createUserForBill.createUserForBill
    events:
      - http:
          path: createuserforbill
          method: post
          cors: true
  restorePasswordForBill:
    handler: api/bills/restorePasswordForBill.restorePasswordForBill
    events:
      - http:
          path: restorepasswordforbill
          method: post
          cors: true
  createReceipt:
    handler: api/receipts/createReceipt.createReceipt
    events:
      - http:
          path: receipt
          method: post
          cors: true
          authorizer: authorize
  getReceipts:
    handler: api/receipts/getReceipts.getReceipts
    events:
      - http:
          path: receipts
          method: get
          cors: true
          authorizer: authorize
  getReceipt:
    handler: api/receipts/getReceipt.getReceipt
    events:
      - http:
          path: receipts/{id}
          method: get
          cors: true
          authorizer: authorize